package me.jianbin00.newsreader.mvp.model.entity;

import com.google.gson.Gson;

import java.util.List;

/**
 * Jianbin Li
 * 2018/10/10
 */
public class NewsResponse
{
    /**
     * status : ok
     * totalResults : 10
     * articles : [{"source":{"id":"bbc-news","name":"BBC News"},"author":"BBC News","title":"Donald Trump and a world of disorder","description":"The Trump administration stands accused of being a bystander to lawlessness around the world.","url":"http://www.bbc.co.uk/news/world-us-canada-45817222","urlToImage":"https://ichef.bbci.co.uk/news/1024/branded_news/16594/production/_103804519_trump_976getty.jpg","publishedAt":"2018-10-10T22:23:37Z","content":"Image copyright Getty Images Image caption Trump has often cut an isolated figure on the world stage At a moment when America has been focussed myopically on the highest court in the land, the Trump administration stands accused of being a bystander to lawles\u2026 [+8218 chars]"},{"source":{"id":"bbc-news","name":"BBC News"},"author":"BBC News","title":"Chinese man faces US aviation spy charges","description":"Prosecutors say Yanjun Xu tried to steal trade secrets from US aviation and aerospace companies.","url":"http://www.bbc.co.uk/news/world-us-canada-45817714","urlToImage":"https://ichef.bbci.co.uk/news/1024/branded_news/139B6/production/_103801308_gettyimages-2793928.jpg","publishedAt":"2018-10-10T21:46:49Z","content":"Image copyright Getty Images Image caption The indictment identifies GE Aviation as a a target of the operation The US justice department has announced charges of economic espionage against a suspected Chinese intelligence officer. Officials say Yanjun Xu tri\u2026 [+1843 chars]"},{"source":{"id":"bbc-news","name":"BBC News"},"author":"BBC News","title":"Will young people bother to vote in US?","description":"Young turnout in the US mid-terms is historically low but there are some signs that things may be different this year.","url":"http://www.bbc.co.uk/news/world-us-canada-45790583","urlToImage":"https://ichef.bbci.co.uk/images/ic/1024x576/p06nhtcq.jpg","publishedAt":"2018-10-10T21:15:16Z","content":"Media caption Hang on, what ARE the US 'mid-terms'? This election has been billed as one in which young people form a powerful voting bloc, propelled by the momentum generated by school shootings earlier in the year, and mobilised by celebrities like Taylor S\u2026 [+6672 chars]"},{"source":{"id":"bbc-news","name":"BBC News"},"author":"BBC News","title":"Limo operator charged over New York crash","description":"The stretch limo was taking a group to a party when it lost control, killing 20 people.","url":"http://www.bbc.co.uk/news/world-us-canada-45817739","urlToImage":"https://ichef.bbci.co.uk/images/ic/1024x576/p06n7gcm.jpg","publishedAt":"2018-10-10T20:56:10Z","content":"Media caption The cause of the crash is unclear The operator of a limousine company involved in a deadly crash in upstate New York on Saturday has been arrested on a charge of negligent homicide. They say the driver did not have a proper licence and the vehic\u2026 [+945 chars]"},{"source":{"id":"bbc-news","name":"BBC News"},"author":"BBC News","title":"US shares suffer sharpest drop in months","description":"The technology-based Nasdaq index falls 4% and S&P 500 marks biggest one-day fall since early February.","url":"http://www.bbc.co.uk/news/business-45815183","urlToImage":"https://ichef.bbci.co.uk/news/1024/branded_news/162CE/production/_103803809_wallstreet.jpg","publishedAt":"2018-10-10T20:36:02Z","content":"Image copyright Getty Images Shares on Wall Street suffered their sharpest one-day falls in months, as investor fears about rising interest rates, inflation, trade tensions intensified. The tech-heavy Nasdaq led the declines, sliding 4%, or 315.9 points, to 7\u2026 [+1710 chars]"},{"source":{"id":"bbc-news","name":"BBC News"},"author":"BBC News","title":"Trump 'demands answers' on missing Saudi","description":"Jamal Khashoggi, a US resident, has not been seen since entering the Saudi consulate in Turkey.","url":"http://www.bbc.co.uk/news/world-europe-45817736","urlToImage":"https://ichef.bbci.co.uk/news/1024/branded_news/39F7/production/_103793841_mediaitem103793840.jpg","publishedAt":"2018-10-10T20:01:58Z","content":"Image copyright Reuters Image caption This image allegedly shows Saudi intelligence officers entering and leaving Turkey via Istanbul airport President Donald Trump has vowed to \"get to the bottom\" of the case of missing Saudi journalist Jamal Khashoggi. Mr T\u2026 [+4166 chars]"},{"source":{"id":"bbc-news","name":"BBC News"},"author":"BBC Sport","title":"Cristiano Ronaldo: Juventus forward says rape claims 'elaborate and deliberate defamation campaign'","description":"Juventus forward Cristiano Ronaldo says rape allegations against him are an \"elaborate and deliberate defamation campaign\".","url":"http://www.bbc.co.uk/sport/football/45817055","urlToImage":"https://ichef.bbci.co.uk/onesport/cps/624/cpsprodpb/13590/production/_97584297_breaking_news.png","publishedAt":"2018-10-10T17:50:43Z","content":"Rape allegations made against Cristiano Ronaldo are a \"defamation campaign based on stolen and easily manipulated digital documents\", according to the player's lawyer Peter Christiansen. Ronaldo, 33, denies assaulting Kathryn Mayorga at a Las Vegas hotel in 2\u2026 [+1487 chars]"},{"source":{"id":"bbc-news","name":"BBC News"},"author":"BBC News","title":"Sears shares falter on bankruptcy fears","description":"The firm is facing a $134m debt payment that is due on Monday.","url":"http://www.bbc.co.uk/news/business-45815179","urlToImage":"https://ichef.bbci.co.uk/news/1024/branded_news/181FA/production/_103801889_sears2.jpg","publishedAt":"2018-10-10T16:29:14Z","content":"Image copyright Getty Images Image caption Sears has closed hundreds of stores in recent years Shares in Sears Holdings plunged by more than 30% on Wednesday following a report that the US retail chain was preparing to file for bankruptcy. The firm was prepar\u2026 [+3052 chars]"},{"source":{"id":"bbc-news","name":"BBC News"},"author":"BBC News","title":"Woman who spent £16m in Harrods revealed","description":"Zamira Hajiyeva, a 55-year-old from Azerbaijan, has been ordered to explain how she got all her money.","url":"http://www.bbc.co.uk/news/uk-45812210","urlToImage":"https://ichef.bbci.co.uk/news/1024/branded_news/8849/production/_103798843_woman3.jpg","publishedAt":"2018-10-10T12:14:11Z","content":"Image caption Zamira Hajiyeva, pictured in 2017, once spent £150,000 in a day at Harrods A woman fighting to keep her £11.5m London home, after becoming the first target for the UK's new anti-corruption law, has been named as Zamira Hajiyeva. Mrs Hajiyeva - w\u2026 [+5575 chars]"},{"source":{"id":"bbc-news","name":"BBC News"},"author":"BBC News","title":"'Monstrous' hurricane set to hit Florida","description":"More than 370,000 people have been ordered to evacuate as Hurricane Michael heads towards Florida.","url":"http://www.bbc.co.uk/news/world-us-canada-45806599","urlToImage":"https://ichef.bbci.co.uk/news/1024/branded_news/133CE/production/_103789787_e7318ab0-a086-4ad4-ad58-d08a680d5a51.jpg","publishedAt":"2018-10-10T03:48:18Z","content":"Image copyright Getty Images Image caption Florida Governor Rick Scott warned state residents that \"this storm could kill you\" Powerful Hurricane Michael is set to make landfall in Florida later on Wednesday, forcing mass evacuations in the southern US state.\u2026 [+6628 chars]"}]
     */

    private String status;
    private int totalResults;
    private List<ArticlesBean> articles;

    public static NewsResponse objectFromData(String str)
    {

        return new Gson().fromJson(str, NewsResponse.class);
    }

    public String getStatus()
    {
        return status;
    }

    public void setStatus(String status)
    {
        this.status = status;
    }

    public int getTotalResults()
    {
        return totalResults;
    }

    public void setTotalResults(int totalResults)
    {
        this.totalResults = totalResults;
    }

    public List<ArticlesBean> getArticles()
    {
        return articles;
    }

    public void setArticles(List<ArticlesBean> articles)
    {
        this.articles = articles;
    }

    public static class ArticlesBean
    {
        /**
         * source : {"id":"bbc-news","name":"BBC News"}
         * author : BBC News
         * title : Donald Trump and a world of disorder
         * description : The Trump administration stands accused of being a bystander to lawlessness around the world.
         * url : http://www.bbc.co.uk/news/world-us-canada-45817222
         * urlToImage : https://ichef.bbci.co.uk/news/1024/branded_news/16594/production/_103804519_trump_976getty.jpg
         * publishedAt : 2018-10-10T22:23:37Z
         * content : Image copyright Getty Images Image caption Trump has often cut an isolated figure on the world stage At a moment when America has been focussed myopically on the highest court in the land, the Trump administration stands accused of being a bystander to lawles… [+8218 chars]
         */

        private SourceBean source;
        private String author;
        private String title;
        private String description;
        private String url;
        private String urlToImage;
        private String publishedAt;
        private String content;

        public static ArticlesBean objectFromData(String str)
        {

            return new Gson().fromJson(str, ArticlesBean.class);
        }

        public SourceBean getSource()
        {
            return source;
        }

        public void setSource(SourceBean source)
        {
            this.source = source;
        }

        public String getAuthor()
        {
            return author;
        }

        public void setAuthor(String author)
        {
            this.author = author;
        }

        public String getTitle()
        {
            return title;
        }

        public void setTitle(String title)
        {
            this.title = title;
        }

        public String getDescription()
        {
            return description;
        }

        public void setDescription(String description)
        {
            this.description = description;
        }

        public String getUrl()
        {
            return url;
        }

        public void setUrl(String url)
        {
            this.url = url;
        }

        public String getUrlToImage()
        {
            return urlToImage;
        }

        public void setUrlToImage(String urlToImage)
        {
            this.urlToImage = urlToImage;
        }

        public String getPublishedAt()
        {
            return publishedAt;
        }

        public void setPublishedAt(String publishedAt)
        {
            this.publishedAt = publishedAt;
        }

        public String getContent()
        {
            return content;
        }

        public void setContent(String content)
        {
            this.content = content;
        }

        public static class SourceBean
        {
            /**
             * id : bbc-news
             * name : BBC News
             */

            private String id;
            private String name;

            public static SourceBean objectFromData(String str)
            {

                return new Gson().fromJson(str, SourceBean.class);
            }

            public String getId()
            {
                return id;
            }

            public void setId(String id)
            {
                this.id = id;
            }

            public String getName()
            {
                return name;
            }

            public void setName(String name)
            {
                this.name = name;
            }
        }
    }
}
